# Generated by Django 4.1.13 on 2025-04-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_accountbackupautomation_backup_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vpn_connectivity',
            field=models.CharField(choices=[('-', 'Unknown'), ('ok', 'Ok'), ('err', 'Error')], default='-', max_length=16, verbose_name='Connectivity'),
        ),
    ]
