# Generated by Django 4.1.13 on 2025-10-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_auto_20250610_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftplog',
            name='encrypt_fields',
            field=models.CharField(default='', max_length=1024, verbose_name='Encrypt fields'),
        ),
        migrations.AddField(
            model_name='ftplog',
            name='encrypt_value',
            field=models.CharField(default='', max_length=1024, verbose_name='Encrypt value'),
        ),
        migrations.AddField(
            model_name='operatelog',
            name='encrypt_fields',
            field=models.CharField(default='', max_length=1024, verbose_name='Encrypt fields'),
        ),
        migrations.AddField(
            model_name='operatelog',
            name='encrypt_value',
            field=models.CharField(default='', max_length=1024, verbose_name='Encrypt value'),
        ),
        migrations.AddField(
            model_name='passwordchangelog',
            name='encrypt_fields',
            field=models.CharField(default='', max_length=1024, verbose_name='Encrypt fields'),
        ),
        migrations.AddField(
            model_name='passwordchangelog',
            name='encrypt_value',
            field=models.CharField(default='', max_length=1024, verbose_name='Encrypt value'),
        ),
        migrations.AddField(
            model_name='userloginlog',
            name='encrypt_fields',
            field=models.CharField(default='', max_length=1024, verbose_name='Encrypt fields'),
        ),
        migrations.AddField(
            model_name='userloginlog',
            name='encrypt_value',
            field=models.CharField(default='', max_length=1024, verbose_name='Encrypt value'),
        ),
    ]
