# Generated by Django 4.1.13 on 2026-02-03 02:16

import common.db.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acls', '0003_datamaskingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandfilteracl',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Meta'),
        ),
        migrations.AddField(
            model_name='commandfilteracl',
            name='reviewers_2',
            field=models.ManyToManyField(blank=True, related_name='command_filter_acl_reviewers_2', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers 2'),
        ),
        migrations.CreateModel(
            name='AssetFileOperateACL',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('priority', models.IntegerField(default=50, help_text='1-100, the lower the value will be match first', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Priority')),
                ('action', models.CharField(default='reject', max_length=64, verbose_name='Action')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('users', common.db.fields.JSONManyToManyField(default=dict, to='users.User', verbose_name='Users')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('assets', common.db.fields.JSONManyToManyField(default=dict, to='assets.Asset', verbose_name='Assets')),
                ('accounts', models.JSONField(default=list, verbose_name='Accounts')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Meta')),
                ('reviewers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Reviewers')),
                ('reviewers_2', models.ManyToManyField(blank=True, related_name='asset_file_operate_acl_reviewers_2', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers 2')),
            ],
            options={
                'verbose_name': 'Asset file operate acl',
                'ordering': ('priority', '-is_active', 'name'),
                'abstract': False,
                'unique_together': {('name', 'org_id')},
            },
        ),
    ]
