# Generated by Django 4.1.13 on 2025-12-24 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acls', '0003_datamaskingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandfilteracl',
            name='reviewers_2',
            field=models.ManyToManyField(blank=True, related_name='command_filter_acl_reviewers_2', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers 2'),
        ),
    ]
