# Generated by Django 4.1.13 on 2025-10-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0010_alter_command_risk_level_alter_session_login_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='encrypt_fields',
            field=models.CharField(default='', max_length=1024, verbose_name='Encrypt fields'),
        ),
        migrations.AddField(
            model_name='command',
            name='encrypt_value',
            field=models.CharField(default='', max_length=1024, verbose_name='Encrypt value'),
        ),
    ]
