# Generated by Django 4.1.13 on 2025-04-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0069_endpoint_sqlserver_port_alter_appprovider_apps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='encrypt_fields',
            field=models.CharField(default='', max_length=1024, verbose_name='Encrypt fields'),
        ),
        migrations.AddField(
            model_name='command',
            name='encrypt_value',
            field=models.CharField(default='', max_length=1024, verbose_name='Encrypt value'),
        ),
    ]
