
SELECT = 'select'
INSERT = 'insert'
UPDATE = 'update'
DELETE = 'delete'
AGGREGATE = 'aggregate'


MIDDLEMAN_TABLE_WHITELIST = {
    'accounts_account',
    'accounts_accounttemplate',
    'accounts_historicalaccount',
    'accounts_virtualaccount',
    'acls_commandfilteracl',
    'acls_commandfilteracl_command_groups',
    'acls_commandfilteracl_reviewers',
    'acls_commandgroup',
    'acls_connectmethodacl',
    'acls_connectmethodacl_reviewers',
    'acls_datamaskingrule',
    'acls_datamaskingrule_reviewers',
    'acls_loginacl',
    'acls_loginacl_reviewers',
    'acls_loginassetacl',
    'acls_loginassetacl_reviewers',
    'assets_asset',
    'assets_asset_directory_services',
    'assets_asset_nodes',
    'assets_cloud',
    'assets_custom',
    'assets_database',
    'assets_device',
    'assets_directoryservice',
    'assets_gpt',
    'assets_host',
    'assets_label',
    'assets_node',
    'assets_platform',
    'assets_protocol',
    'assets_web',
    'assets_zone',
    'labels_label',
    'labels_labeledresource',
    'orgs_organization',
    'perms_assetpermission',
    'perms_assetpermission_assets',
    'perms_assetpermission_nodes',
    'perms_assetpermission_user_groups',
    'perms_assetpermission_users',
    'rbac_menupermission',
    'rbac_role_permissions',
    'rbac_role',
    'rbac_rolebinding',
    'users_user',
    'users_user_groups',
    'users_user_user_permissions',
    'users_usergroup',
}
