# Generated by Django 4.1.13 on 2025-07-23 09:03

import common.db.fields
import common.utils.django
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_user_lark_id_alter_user_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_expired',
            field=models.DateTimeField(blank=True, db_index=True, default=common.utils.django.user_date_expired_default, null=True, verbose_name='Date expired'),
        ),
        migrations.CreateModel(
            name='UKey',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('u_key_serial', models.CharField(max_length=128, unique=True, verbose_name='USBKey Serial')),
                ('u_key_public_key', common.db.fields.EncryptTextField(verbose_name='USBKey Public Key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_usb_key', to=settings.AUTH_USER_MODEL, verbose_name='USBKey Serial')),
            ],
            options={
                'verbose_name': 'User UKey',
            },
        ),
    ]
