# Generated by Django 4.1.13 on 2025-04-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_user_lark_id_alter_user_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usb_key_public_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='UKey public key'),
        ),
        migrations.AddField(
            model_name='user',
            name='usb_key_serial',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='UKey Serial'),
        ),
    ]
