# Generated by Django 4.1.13 on 2025-12-24 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0019_alter_asset_connectivity'),
        ('tickets', '0004_replace_assignees_to_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyAssetFileTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticket')),
                ('apply_login_account', models.CharField(default='', max_length=128, verbose_name='Login account')),
                ('apply_login_asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset', verbose_name='Login asset')),
                ('apply_login_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Login user')),
            ],
            options={
                'verbose_name': 'Apply Asset File Operate Ticket',
            },
            bases=('tickets.ticket',),
        ),
    ]
