# Generated by Django 4.1.13 on 2025-04-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0128_auto_20240514_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='vpn_connectivity',
            field=models.CharField(choices=[('-', 'Unknown'), ('ok', 'Ok'), ('err', 'Error')], default='-', max_length=16, verbose_name='Connectivity'),
        ),
    ]
