# Generated by Django 4.1.13 on 2025-06-14 10:03
import time

from django.db import migrations, models


def set_old_assets_weight_value(apps, schema_editor):
    asset_model = apps.get_model('assets', 'Asset')

    count, weight, bulk_size = 0, 0, 1000
    while True:
        assets = asset_model.objects.all()[count:count + bulk_size]
        if not assets:
            break

        start = time.time()
        for asset in assets:
            asset.weight = weight
            weight += 1000
        asset_model.objects.bulk_update(assets, ['weight'])
        count += len(assets)
        print(f"Update {len(assets)} assets weight, using: {time.time() - start:.2f}s")


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0128_auto_20240514_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='weight',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Weight'),
        ),
        migrations.RunPython(set_old_assets_weight_value)
    ]
