# Generated by Django 4.1.13 on 2025-03-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0128_auto_20240514_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpt',
            options={'verbose_name': 'GPT'},
        ),
    ]
