# Generated by Django 4.1.13 on 2026-03-16 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20250626_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupermission',
            options={'default_permissions': [], 'permissions': [('view_console', 'Can view console view'), ('view_control-hub', 'Can view control hub view'), ('view_pam', 'Can view pam view'), ('view_audit', 'Can view audit view'), ('view_workbench', 'Can view workbench view'), ('view_webterminal', 'Can view web terminal'), ('view_filemanager', 'Can view file manager'), ('view_systemtools', 'Can view System Tools'), ('view_userloginreport', 'Can view user login report'), ('view_userchangepasswordreport', 'Can view user change password report'), ('view_assetstatisticsreport', 'Can view asset statistics report'), ('view_assetactivityreport', 'Can view asset activity report'), ('view_accountstatisticsreport', 'Can view account statistics report'), ('view_accountautomationreport', 'Can view account automation report')], 'verbose_name': 'Menu permission'},
        ),
    ]
