# Generated by Django 4.1.13 on 2025-06-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0014_auto_20231208_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupermission',
            options={'default_permissions': [], 'permissions': [('view_console', 'Can view console view'), ('view_control-hub', 'Can view control hub view'), ('view_audit', 'Can view audit view'), ('view_workbench', 'Can view workbench view'), ('view_webterminal', 'Can view web terminal'), ('view_filemanager', 'Can view file manager'), ('view_systemtools', 'Can view System Tools')], 'verbose_name': 'Menu permission'},
        ),
    ]
